from __future__ import annotations

from .models import CatAction, CatAppearance, CatBreed


CAT_BREEDS: dict[str, CatBreed] = {
    "siamese": CatBreed(
        id="siamese",
        display_name="暹罗猫",
        appearance=CatAppearance(
            body=(232, 217, 188),
            belly=(246, 238, 218),
            accent=(79, 58, 54),
            stripe=(106, 78, 70),
            eye=(70, 170, 220),
            pattern="points",
        ),
        personality="话痨、粘人、活泼",
        behavior_style="经常叫，喜欢靠近鼠标",
        special_action="不停喵喵叫",
        behavior_weights={
            CatAction.IDLE: 18,
            CatAction.WALK: 24,
            CatAction.SLEEP: 8,
            CatAction.HAPPY: 18,
            CatAction.ANNOYED: 6,
            CatAction.SPECIAL: 26,
        },
        speed_bias=1.15,
        affection_bias=1.25,
    ),
    "american_shorthair": CatBreed(
        id="american_shorthair",
        display_name="美短猫",
        appearance=CatAppearance(
            body=(174, 181, 184),
            belly=(224, 228, 228),
            accent=(93, 99, 102),
            stripe=(96, 103, 108),
            eye=(95, 170, 90),
            pattern="tabby",
        ),
        personality="友好、稳定、好奇",
        behavior_style="经常探索屏幕边缘",
        special_action="蹲坐洗脸",
        behavior_weights={
            CatAction.IDLE: 22,
            CatAction.WALK: 28,
            CatAction.SLEEP: 14,
            CatAction.HAPPY: 18,
            CatAction.ANNOYED: 5,
            CatAction.SPECIAL: 13,
        },
    ),
    "ragdoll": CatBreed(
        id="ragdoll",
        display_name="布偶猫",
        appearance=CatAppearance(
            body=(238, 230, 218),
            belly=(250, 246, 238),
            accent=(166, 134, 124),
            stripe=(205, 184, 176),
            eye=(82, 145, 230),
            pattern="soft",
        ),
        personality="温顺、慵懒、亲人",
        behavior_style="更爱睡觉、翻肚皮",
        special_action="躺倒翻肚皮",
        behavior_weights={
            CatAction.IDLE: 18,
            CatAction.WALK: 10,
            CatAction.SLEEP: 34,
            CatAction.HAPPY: 22,
            CatAction.ANNOYED: 3,
            CatAction.SPECIAL: 13,
        },
        speed_bias=0.72,
        affection_bias=1.2,
    ),
    "black": CatBreed(
        id="black",
        display_name="黑猫",
        appearance=CatAppearance(
            body=(25, 25, 29),
            belly=(40, 40, 46),
            accent=(10, 10, 14),
            stripe=(67, 67, 76),
            eye=(238, 210, 76),
            pattern="solid",
        ),
        personality="神秘、安静、机敏",
        behavior_style="喜欢突然出现、蹲坐观察",
        special_action="缩成黑影或突然睁眼",
        behavior_weights={
            CatAction.IDLE: 30,
            CatAction.WALK: 18,
            CatAction.SLEEP: 16,
            CatAction.HAPPY: 10,
            CatAction.ANNOYED: 8,
            CatAction.SPECIAL: 18,
        },
        speed_bias=1.05,
    ),
    "lihua": CatBreed(
        id="lihua",
        display_name="狸花猫",
        appearance=CatAppearance(
            body=(139, 118, 86),
            belly=(211, 195, 165),
            accent=(78, 62, 44),
            stripe=(64, 52, 38),
            eye=(112, 180, 78),
            pattern="tabby",
        ),
        personality="独立、聪明、活跃",
        behavior_style="喜欢跳跃、抓屏幕边缘",
        special_action="扑向鼠标",
        behavior_weights={
            CatAction.IDLE: 16,
            CatAction.WALK: 32,
            CatAction.SLEEP: 9,
            CatAction.HAPPY: 14,
            CatAction.ANNOYED: 8,
            CatAction.SPECIAL: 21,
        },
        speed_bias=1.35,
        annoyance_bias=1.08,
    ),
    "tortoiseshell": CatBreed(
        id="tortoiseshell",
        display_name="玳瑁猫",
        appearance=CatAppearance(
            body=(55, 45, 38),
            belly=(193, 112, 58),
            accent=(28, 25, 22),
            stripe=(226, 144, 71),
            eye=(119, 190, 92),
            pattern="tortoise",
        ),
        personality="傲娇、情绪丰富",
        behavior_style="随机行为较多，偶尔不理人",
        special_action="扭头不理用户",
        behavior_weights={
            CatAction.IDLE: 18,
            CatAction.WALK: 18,
            CatAction.SLEEP: 14,
            CatAction.HAPPY: 14,
            CatAction.ANNOYED: 16,
            CatAction.SPECIAL: 20,
        },
        speed_bias=1.0,
        annoyance_bias=1.25,
    ),
}


def get_breed(breed_id: str) -> CatBreed:
    return CAT_BREEDS.get(breed_id, CAT_BREEDS["american_shorthair"])
